version: '3.8' # docker-compose

services:
  web:
    container_name: web
    image: nginx
    ports:
      - 8000:80
    volumes:
      - /home/dlucchesi/projects/docker/myglic-docker/web/:/usr/share/nginx/html/:ro
    depends_on:
      - app


  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: myglicapp.docker
    container_name: app
    ports:
      - 8180:8180
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_myglic
      - SPRING_DATASOURCE_USERNAME=usr_myglic
      - SPRING_DATASOURCE_PASSWORD=654321
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=dev

  db:
    image: 'postgres:14.1-alpine'
    # restart: always
    restart: unless-stopped
    container_name: db
    volumes:
      - /home/dlucchesi/data:/var/lib/postgresql/data:rw
      # script to init load -> create databases
      - /home/dlucchesi/projects/docker/myglic-docker/db/create_postgresql.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=usr_myglic
      - POSTGRES_PASSWORD=654321    

volumes:
  db:
    driver: local
